### ISSUE TITLE
Peer review 1: Övergripande

### ISSUE THREAD

**Issue by lw222gu** [kk222hk/1DV450_kk222hk#1]
Jag har nu kikat på din applikation och listar vad jag tycker är bra nedan. För förbättringsförslag skapar jag enskilda issues. Hör av dig om något är oklart! Överlag har jag inte mycket att påpeka som bör förändras, utan jag tycker att detta är jättebra, och jag inser snarare hur mycket knasigheter jag själv gjort i min kod :-)

Applikationen har jag kört via länken hos Heroku, och koden har jag kikat på från release v1.1. Det finns en hel del filer i releasen som jag tror har att göra med labb 2 - dessa har jag bortsett från helt och hållet.

# Bra delar i applikationen
* Bra design. Enkel och stilren. Det är enkelt att som användare förstå vad som ska göras.
* Bra hantering av felmeddelanden. De beskriver också tydligt vad som är orsaken till felet i de flesta fallen. Du använder felen som genereras från valideringen, i stället för som jag gjort att skapa fel som egna flashmeddelanden. Det känns ju betydligt mer korrekt så som du gjort. Det enda jag tjänade på att göra på mitt sätt var att jag kan använda mig av koden för flashmeddelanden i layoutfilen oavsett om det är ett fel- eller rättmeddelande, och har ingen partiell errors-vy, men måste i stället skriva fel som redan finns i min controller...
* Bra "rättmeddelanden".
* Fungerar bra att lägga till och ta bort applikationer som vanlig användare. Bra att en bekräftelse krävs vid borttagning.
* Fungerar bra att ta bort applikationer som admin.
* Åtkomstkontroller på länkar. Man kommer inte åt det man inte ska komma åt.
* Hittar ingen upprepad kod.
* Hittar ingen oanvänd kod bortsett från ett bortkommenterat test för keys.
* Lätt att följa commits.
* RESTful routes, och controllermetoder.
* Bra namngivning.
* Det finns inte jättemycket kommentarer, men jag tycker inte heller att det behövs - koden är självförklarande och där kommentarer används är de tydliga.
* Indenterad kod och välstrukturerade filer.
* Du använder Rubys syntax bra, t.ex. med `unless` i stället för `if !`.

**Comment by kk222hk** [comment]
Tack för bra feedback! Ska kika på förbättringsförslagen

**Comment by 1dv450** [comment]
Bra feedback!
