### ISSUE TITLE
Favor unless over if for negative conditions

### ISSUE THREAD

**Issue by OskarKlintrot** [kk222hk/1DV450_kk222hk#10]
This is a bit picky but on line 18 in `key.rb` you use `if !`, could be refactored to the preferred way of using unless/if in Ruby to:
``` Ruby
break token unless Key.exists?(key_value: token)
```

**Comment by kk222hk** [comment]
Cool, thanks! I'm still not completely used to the ruby syntax so I miss these tricks sometimes

**Comment by OskarKlintrot** [comment]
This is a great linter to find such tricks; http://batsov.com/rubocop/ :sunglasses:

**Comment by kk222hk** [comment]
Awesome!
