### ISSUE TITLE
How is duplicates handled?

### ISSUE THREAD

**Issue by OskarKlintrot** [kk222hk/1DV450_kk222hk#13]
I noticed that I can create multiple catches with the same info. I guess it makes sense since me and my pals can catch a lot of eels in the same place but is there anyway to distinguish them from each other? Or maybe it should be some limitations for how many/how often you can catch those eels?

**Comment by kk222hk** [comment]
That's true. I suppose there might be some edge cases where you catch several fishes with the same species and dimensions in the same position.

But I added a check so if you add an identical fish 3 times, you get a duplication error. Feels like an allright compromise to stop obvious duplication/spam.
