### ISSUE TITLE
No authentication before deleting catches

### ISSUE THREAD

**Issue by OskarKlintrot** [kk222hk/1DV450_kk222hk#14]
I noticed that you had already fixed this [issue](https://github.com/kk222hk/1DV450_kk222hk/commit/5825e8350757a2bb3e1b7952248aaa885d0028e6) but it's not in the release so I will create an issue for it anyway. An idea could be to use
```Ruby
before_action :authenticate
```
in a `BaseController` that inherit from `ApplicationController` that all controller for the API inherit from. Then for methods where you don't need to be authenticated you can use
```Ruby
skip_before_action :authenticate, only: [:index, :show]
```
to disable the authentication. This way the methods needs authentication unless you specify otherwise so if you forget something again it's not opening up vulnerabilities in your application.

**Comment by kk222hk** [comment]
Neat idea, implemented this. Good for "tankspridda" developers like me. :) Thanks for the feedback btw, good stuff.
