### ISSUE TITLE
No way of creating new users

### ISSUE THREAD

**Issue by OskarKlintrot** [kk222hk/1DV450_kk222hk#17]
There is no method in `UserController` for creating new users.

**Comment by kk222hk** [comment]
I've been following the requirements so there is not support for that. "Det är OK att hårdkoda slutanvändarnas uppgifter i tjänsten".

**Comment by OskarKlintrot** [comment]
Ah, sorry! I forgot that! It's getting late! :sleeping:

**Comment by kk222hk** [comment]
Would be neat with register functionality tho! But time is kind of tight with the project course

**Comment by OskarKlintrot** [comment]
I just did a copy-past from previous create-methods I had done, took like 5 min :stuck_out_tongue:
