### ISSUE TITLE
Peer-review #3 - Validering av fisk

### ISSUE THREAD

**Issue by ks222rt** [kk222hk/1DV450_kk222hk#21]
Inget större problem bara att felmeddelande säger fel. Skriver jag in ett tal på vikt eller längd som är över 500 så säger felmeddelandet: "Längden måste vara högre än 500" & "Vikten måste vara högre än 500". 

Antar det skall stå lägre, som sagt inget större utan bara något jag märkte när jag skulle skapa en firre.

**Comment by kk222hk** [comment]
Helt rätt! Fixat till det nu :beers:
