### ISSUE TITLE
Peer-review #3 - Manipulering av URL vid fiskedetalj

### ISSUE THREAD

**Issue by ks222rt** [kk222hk/1DV450_kk222hk#22]
Har man valt att visa en specifik fisks detaljer och sedan manipulerar url:fen från till exempel: 

http://kk222hk.github.io/#/fish_catches/120  
till ->
http://kk222hk.github.io/#/fish_catches/12012

Så visas ingen information då den fisken inte existerar men sidan visar heller inget felmeddelande. Skulle vara bra för en användare att se ett meddelande om att det inte gick att hämta den resursen eller dylikt.

**Comment by kk222hk** [comment]
Sant! Lade till ett meddelande när en fångst inte hittas
