### ISSUE TITLE
Peer-review #3 - Sammanfattning

### ISSUE THREAD

**Issue by ks222rt** [kk222hk/1DV450_kk222hk#23]
Tjena!

**Installation**  
Din applikation var den lättaste applikationen att få igång då den fanns i liveversion. Inte för att det är mycket jobb att få igång den lokalt men det sparar tid. 

**Kodkvalitén**
Du har grupperat varje funktionell del i olika mappar (t.ex. fiskar och inloggning) vilket gjorde det lätt att hitta specifika delar i clientmappen. Du har även skrivit fruktansvärt bra kommentarer som gjorde det lätt att förstå vad varje funktion gör (skall ta det vidare till mitt projekt). Även bra namngivelser.

**Funktionalitet**  
Du har fått med all funktionalitet som skall finnas med. Extra plus för att du zoomar in kartan på en specifik fisk jag har valt att visa detaljer på. Enda jag kan klaga på är om man manipulerar url (se separat issue), dock inget större problem egentligen men kan vara bra för en ovan användare om det skulle hända för dem.  

**Design**  
Snygg och stilren design. Man förstå vad som händer hela tiden vilket är bra för en ovan användare. Snyggt att zooma in på en specifik fisk och se fiskar som finns i närheten. 
Den responsiva delen fungerar bra.  

**Sammanfattning**  
Finns inga större fel med den utan bara de 2 små issuses jag skapade. Bra jobbat med clientapplikationen.

**Comment by kk222hk** [comment]
Hej, tack för feedback!
