### ISSUE TITLE
Peer review 1: Svengelska

### ISSUE THREAD

**Issue by lw222gu** [kk222hk/1DV450_kk222hk#6]
Lite svengelska över det hela. Engelska och svenska blandas. Svenska används överallt förutom vid labels på startsidan, Log in/Log out och datumet då en api-nyckel skapades. Välj ett språk. Inget avgörande för applikationen, men det gör ju det lättare för användaren.

**Comment by kk222hk** [comment]
Helt rätt! Hade lite otur när jag tänkte när jag namngav saker, fixat nu
