### ISSUE TITLE
The postman collection needs to be looked over

### ISSUE THREAD

**Issue by OskarKlintrot** [kk222hk/1DV450_kk222hk#7]
In the postman collection there is a JWT token in some of the GET-calls but it makes no differens if I remove them. Is the authentication broken or is the Postman collection cluttered? It could also be a very good idea to put both the URL and the JWT token in an environment to make it easier to test. Now I had to change the URL and token in all places instead of just change it in one place. I guess you have to do the same when you are testing your app locally!

**Comment by OskarKlintrot** [comment]
Here's my changes that I have done in order to make it easier to test the API, might be useful for you as well: https://www.getpostman.com/collections/4d02b12b0da0acf43378

**Comment by OskarKlintrot** [comment]
I don't think you can share environments but below is both a print screen and a zip with the environment.
![image](https://cloud.githubusercontent.com/assets/6783879/13430561/d0e86dc4-dfc5-11e5-969b-75a1b3dc4258.png)
[fishing.zip](https://github.com/kk222hk/1DV450_kk222hk/files/152967/fishing.zip)

**Comment by kk222hk** [comment]
GET-requests don't need authentication, my mistake. Environments is a nice solution, I'll borrow your screenshot and .zip :)
