### ISSUE TITLE
Can't authenticate with API-key

### ISSUE THREAD

**Issue by OskarKlintrot** [kk222hk/1DV450_kk222hk#8]
The API-key is not in the seed and when I put it in the seed I still get a 401.

**Comment by OskarKlintrot** [comment]
Found it, the keys in the seed does absolutely nothing, they are generated later on.

**Comment by kk222hk** [comment]
That's true, I forgot that the keys are generated with a before_save. I clarified it in the API documentation.

**Comment by OskarKlintrot** [comment]
I did a fulhack in my app to make sure I have a key that I can use for testing: https://github.com/OskarKlintrotSkolarbeteWP14/1dv450-oklib08-webbramverk/blob/master/apikey_dashboard/app/helpers/apikey_dashboard/keys_helper.rb#L8-L10

Might be something to use, just remember to remove it before production!
