### ISSUE TITLE
Don't sleep on the spacebar

### ISSUE THREAD

**Issue by OskarKlintrot** [kk222hk/1DV450_kk222hk#9]
`fish_catch.rb` line 20, 90 spaces. Seriously?!

**Comment by kk222hk** [comment]
Yeah that line got pretty long and I wasn't sure where to break it up. I did it on one line now instead, do you think it looks better?

**Comment by OskarKlintrot** [comment]
I did a PR with code that is intendent the way Rubocop want's it to be. Good or not is another discussion :smile:

**Comment by kk222hk** [comment]
I can't distrust something named Rubocop so I merged it

**Comment by OskarKlintrot** [comment]
There is however something weird with the format of the document (at least the one I got from git and is using in Atom, I did the edit directly on github for the PR). It says the indentation is -15 spaces, at least it's lesser than 90!

**Comment by OskarKlintrot** [comment]
Haha, that's very true!

**Comment by OskarKlintrot** [comment]
There is however something weird with the format of the document (at least the one I got from git and is using in Atom, I did the edit directly on github for the PR). It says the indentation is -15 spaces, at least it's lesser than 90!
